SELECT Operacion,Linea_de_Negocio,Producto
INTO	OPERACIONES.DBO.FIC_MARCA
FROM CEDENTES.DBO.FINANCOOP_DEUDA
WHERE FECHA_CARGA=(SELECT MAX(FECHA_CARGA) FROM CEDENTES.DBO.FINANCOOP_DEUDA)
GROUP BY Operacion,Linea_de_Negocio,Producto
