INSERT INTO FIC_MARCA SELECT Operacion,Linea_de_Negocio,Producto	
FROM CEDENTES.DBO.FINANCOOP_DEUDA
WHERE FECHA_CARGA=(SELECT MAX(FECHA_CARGA) FROM CEDENTES.DBO.FINANCOOP_DEUDA)
GROUP BY Operacion,Linea_de_Negocio,Producto
